export interface CompoundPreviewSeed {
    imports: string;
    componentTag: string;
}

interface SeedDefinition {
    componentName: string;
    requiredExports: string[];
    imports: string;
    componentTag: string;
}

function seed(definition: SeedDefinition): SeedDefinition {
    return definition;
}

const SEEDS: SeedDefinition[] = [
    seed({
        componentName: 'Accordion',
        requiredExports: ['AccordionItem', 'AccordionTrigger', 'AccordionContent'],
        imports: 'import { AccordionItem as PreviewAccordionItem, AccordionTrigger as PreviewAccordionTrigger, AccordionContent as PreviewAccordionContent } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent type="single" collapsible {...previewProps}>
              <PreviewAccordionItem value="item-1">
                <PreviewAccordionTrigger>What is included in this preview?</PreviewAccordionTrigger>
                <PreviewAccordionContent>
                  Placeholder content generated by Visual Edit so compound components render with a meaningful structure.
                </PreviewAccordionContent>
              </PreviewAccordionItem>
              <PreviewAccordionItem value="item-2">
                <PreviewAccordionTrigger>Can I replace this content?</PreviewAccordionTrigger>
                <PreviewAccordionContent>
                  Yes. This seeded preview exists only for browser visualization and does not change the imported component source.
                </PreviewAccordionContent>
              </PreviewAccordionItem>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'AlertDialog',
        requiredExports: ['AlertDialogTrigger', 'AlertDialogContent', 'AlertDialogHeader', 'AlertDialogFooter', 'AlertDialogTitle', 'AlertDialogDescription', 'AlertDialogAction', 'AlertDialogCancel'],
        imports: 'import { AlertDialogTrigger as PreviewAlertDialogTrigger, AlertDialogContent as PreviewAlertDialogContent, AlertDialogHeader as PreviewAlertDialogHeader, AlertDialogFooter as PreviewAlertDialogFooter, AlertDialogTitle as PreviewAlertDialogTitle, AlertDialogDescription as PreviewAlertDialogDescription, AlertDialogAction as PreviewAlertDialogAction, AlertDialogCancel as PreviewAlertDialogCancel } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewAlertDialogTrigger asChild>
                <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Open alert dialog</button>
              </PreviewAlertDialogTrigger>
              <PreviewAlertDialogContent>
                <PreviewAlertDialogHeader>
                  <PreviewAlertDialogTitle>Confirm this action</PreviewAlertDialogTitle>
                  <PreviewAlertDialogDescription>
                    Use this seeded content to verify spacing, hierarchy, and modal interaction before replacing it with project content.
                  </PreviewAlertDialogDescription>
                </PreviewAlertDialogHeader>
                <PreviewAlertDialogFooter>
                  <PreviewAlertDialogCancel>Cancel</PreviewAlertDialogCancel>
                  <PreviewAlertDialogAction>Continue</PreviewAlertDialogAction>
                </PreviewAlertDialogFooter>
              </PreviewAlertDialogContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Breadcrumb',
        requiredExports: ['BreadcrumbList', 'BreadcrumbItem', 'BreadcrumbLink', 'BreadcrumbPage', 'BreadcrumbSeparator'],
        imports: 'import { BreadcrumbList as PreviewBreadcrumbList, BreadcrumbItem as PreviewBreadcrumbItem, BreadcrumbLink as PreviewBreadcrumbLink, BreadcrumbPage as PreviewBreadcrumbPage, BreadcrumbSeparator as PreviewBreadcrumbSeparator } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewBreadcrumbList>
                <PreviewBreadcrumbItem>
                  <PreviewBreadcrumbLink href="#">Dashboard</PreviewBreadcrumbLink>
                </PreviewBreadcrumbItem>
                <PreviewBreadcrumbSeparator />
                <PreviewBreadcrumbItem>
                  <PreviewBreadcrumbLink href="#">Components</PreviewBreadcrumbLink>
                </PreviewBreadcrumbItem>
                <PreviewBreadcrumbSeparator />
                <PreviewBreadcrumbItem>
                  <PreviewBreadcrumbPage>Preview</PreviewBreadcrumbPage>
                </PreviewBreadcrumbItem>
              </PreviewBreadcrumbList>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Card',
        requiredExports: ['CardHeader', 'CardTitle', 'CardDescription', 'CardContent', 'CardFooter'],
        imports: 'import { CardHeader as PreviewCardHeader, CardTitle as PreviewCardTitle, CardDescription as PreviewCardDescription, CardContent as PreviewCardContent, CardFooter as PreviewCardFooter } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewCardHeader>
                <PreviewCardTitle>Preview Card</PreviewCardTitle>
                <PreviewCardDescription>Seeded content helps validate spacing and hierarchy.</PreviewCardDescription>
              </PreviewCardHeader>
              <PreviewCardContent>
                <p className="text-sm text-muted-foreground">Replace this placeholder with real project content after insertion.</p>
              </PreviewCardContent>
              <PreviewCardFooter>
                <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Primary action</button>
              </PreviewCardFooter>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Collapsible',
        requiredExports: ['CollapsibleTrigger', 'CollapsibleContent'],
        imports: 'import { CollapsibleTrigger as PreviewCollapsibleTrigger, CollapsibleContent as PreviewCollapsibleContent } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <div className="flex items-center justify-between gap-4">
                <div>
                  <div className="text-sm font-medium">Component details</div>
                  <div className="text-sm text-muted-foreground">Toggle to inspect the collapsed content.</div>
                </div>
                <PreviewCollapsibleTrigger asChild>
                  <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Toggle</button>
                </PreviewCollapsibleTrigger>
              </div>
              <PreviewCollapsibleContent className="pt-4 text-sm text-muted-foreground">
                Placeholder content generated to make the collapsible preview interactive and understandable.
              </PreviewCollapsibleContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'ContextMenu',
        requiredExports: ['ContextMenuTrigger', 'ContextMenuContent', 'ContextMenuItem'],
        imports: 'import { ContextMenuTrigger as PreviewContextMenuTrigger, ContextMenuContent as PreviewContextMenuContent, ContextMenuItem as PreviewContextMenuItem } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewContextMenuTrigger className="flex min-h-28 items-center justify-center rounded-lg border border-dashed border-gray-300 text-sm text-muted-foreground">
                Right click this surface
              </PreviewContextMenuTrigger>
              <PreviewContextMenuContent>
                <PreviewContextMenuItem>Open</PreviewContextMenuItem>
                <PreviewContextMenuItem>Duplicate</PreviewContextMenuItem>
                <PreviewContextMenuItem>Archive</PreviewContextMenuItem>
              </PreviewContextMenuContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Dialog',
        requiredExports: ['DialogTrigger', 'DialogContent', 'DialogHeader', 'DialogTitle', 'DialogDescription', 'DialogFooter'],
        imports: 'import { DialogTrigger as PreviewDialogTrigger, DialogContent as PreviewDialogContent, DialogHeader as PreviewDialogHeader, DialogTitle as PreviewDialogTitle, DialogDescription as PreviewDialogDescription, DialogFooter as PreviewDialogFooter } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewDialogTrigger asChild>
                <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Open dialog</button>
              </PreviewDialogTrigger>
              <PreviewDialogContent>
                <PreviewDialogHeader>
                  <PreviewDialogTitle>Preview dialog</PreviewDialogTitle>
                  <PreviewDialogDescription>
                    This seeded dialog demonstrates default structure and interaction inside the browser preview.
                  </PreviewDialogDescription>
                </PreviewDialogHeader>
                <div className="text-sm text-muted-foreground">You can replace this body with your own content after insertion.</div>
                <PreviewDialogFooter>
                  <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Save changes</button>
                </PreviewDialogFooter>
              </PreviewDialogContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'DropdownMenu',
        requiredExports: ['DropdownMenuTrigger', 'DropdownMenuContent', 'DropdownMenuItem'],
        imports: 'import { DropdownMenuTrigger as PreviewDropdownMenuTrigger, DropdownMenuContent as PreviewDropdownMenuContent, DropdownMenuItem as PreviewDropdownMenuItem } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewDropdownMenuTrigger asChild>
                <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Open menu</button>
              </PreviewDropdownMenuTrigger>
              <PreviewDropdownMenuContent>
                <PreviewDropdownMenuItem>Profile</PreviewDropdownMenuItem>
                <PreviewDropdownMenuItem>Billing</PreviewDropdownMenuItem>
                <PreviewDropdownMenuItem>Log out</PreviewDropdownMenuItem>
              </PreviewDropdownMenuContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'HoverCard',
        requiredExports: ['HoverCardTrigger', 'HoverCardContent'],
        imports: 'import { HoverCardTrigger as PreviewHoverCardTrigger, HoverCardContent as PreviewHoverCardContent } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewHoverCardTrigger asChild>
                <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">@visual-edit</button>
              </PreviewHoverCardTrigger>
              <PreviewHoverCardContent className="w-80">
                <div className="space-y-2">
                  <div className="text-sm font-semibold">Hover card preview</div>
                  <p className="text-sm text-muted-foreground">This seeded content keeps the component intelligible before you wire in real data.</p>
                </div>
              </PreviewHoverCardContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Menubar',
        requiredExports: ['MenubarMenu', 'MenubarTrigger', 'MenubarContent', 'MenubarItem'],
        imports: 'import { MenubarMenu as PreviewMenubarMenu, MenubarTrigger as PreviewMenubarTrigger, MenubarContent as PreviewMenubarContent, MenubarItem as PreviewMenubarItem } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewMenubarMenu>
                <PreviewMenubarTrigger>File</PreviewMenubarTrigger>
                <PreviewMenubarContent>
                  <PreviewMenubarItem>New tab</PreviewMenubarItem>
                  <PreviewMenubarItem>Share</PreviewMenubarItem>
                  <PreviewMenubarItem>Export</PreviewMenubarItem>
                </PreviewMenubarContent>
              </PreviewMenubarMenu>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'NavigationMenu',
        requiredExports: ['NavigationMenuList', 'NavigationMenuItem', 'NavigationMenuTrigger', 'NavigationMenuContent', 'NavigationMenuLink'],
        imports: 'import { NavigationMenuList as PreviewNavigationMenuList, NavigationMenuItem as PreviewNavigationMenuItem, NavigationMenuTrigger as PreviewNavigationMenuTrigger, NavigationMenuContent as PreviewNavigationMenuContent, NavigationMenuLink as PreviewNavigationMenuLink } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewNavigationMenuList>
                <PreviewNavigationMenuItem>
                  <PreviewNavigationMenuTrigger>Resources</PreviewNavigationMenuTrigger>
                  <PreviewNavigationMenuContent>
                    <div className="grid gap-2 p-4 md:w-[320px]">
                      <PreviewNavigationMenuLink href="#">Documentation</PreviewNavigationMenuLink>
                      <PreviewNavigationMenuLink href="#">Components</PreviewNavigationMenuLink>
                      <PreviewNavigationMenuLink href="#">Examples</PreviewNavigationMenuLink>
                    </div>
                  </PreviewNavigationMenuContent>
                </PreviewNavigationMenuItem>
              </PreviewNavigationMenuList>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Pagination',
        requiredExports: ['PaginationContent', 'PaginationItem', 'PaginationLink', 'PaginationPrevious', 'PaginationNext'],
        imports: 'import { PaginationContent as PreviewPaginationContent, PaginationItem as PreviewPaginationItem, PaginationLink as PreviewPaginationLink, PaginationPrevious as PreviewPaginationPrevious, PaginationNext as PreviewPaginationNext } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewPaginationContent>
                <PreviewPaginationItem>
                  <PreviewPaginationPrevious href="#" />
                </PreviewPaginationItem>
                <PreviewPaginationItem>
                  <PreviewPaginationLink href="#" isActive>1</PreviewPaginationLink>
                </PreviewPaginationItem>
                <PreviewPaginationItem>
                  <PreviewPaginationLink href="#">2</PreviewPaginationLink>
                </PreviewPaginationItem>
                <PreviewPaginationItem>
                  <PreviewPaginationNext href="#" />
                </PreviewPaginationItem>
              </PreviewPaginationContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Popover',
        requiredExports: ['PopoverTrigger', 'PopoverContent'],
        imports: 'import { PopoverTrigger as PreviewPopoverTrigger, PopoverContent as PreviewPopoverContent } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewPopoverTrigger asChild>
                <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Open popover</button>
              </PreviewPopoverTrigger>
              <PreviewPopoverContent className="w-80">
                <div className="space-y-2">
                  <div className="text-sm font-semibold">Preview popover</div>
                  <p className="text-sm text-muted-foreground">A seeded popover makes spacing and positioning easier to validate.</p>
                </div>
              </PreviewPopoverContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'RadioGroup',
        requiredExports: ['RadioGroupItem'],
        imports: 'import { RadioGroupItem as PreviewRadioGroupItem } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent className="gap-3" {...previewProps}>
              <label className="flex items-center gap-3 text-sm">
                <PreviewRadioGroupItem value="compact" />
                Compact
              </label>
              <label className="flex items-center gap-3 text-sm">
                <PreviewRadioGroupItem value="comfortable" />
                Comfortable
              </label>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Select',
        requiredExports: ['SelectTrigger', 'SelectValue', 'SelectContent', 'SelectItem'],
        imports: 'import { SelectTrigger as PreviewSelectTrigger, SelectValue as PreviewSelectValue, SelectContent as PreviewSelectContent, SelectItem as PreviewSelectItem } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewSelectTrigger className="w-full">
                <PreviewSelectValue placeholder="Choose a plan" />
              </PreviewSelectTrigger>
              <PreviewSelectContent>
                <PreviewSelectItem value="starter">Starter</PreviewSelectItem>
                <PreviewSelectItem value="pro">Pro</PreviewSelectItem>
                <PreviewSelectItem value="enterprise">Enterprise</PreviewSelectItem>
              </PreviewSelectContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Sheet',
        requiredExports: ['SheetTrigger', 'SheetContent', 'SheetHeader', 'SheetTitle', 'SheetDescription', 'SheetFooter'],
        imports: 'import { SheetTrigger as PreviewSheetTrigger, SheetContent as PreviewSheetContent, SheetHeader as PreviewSheetHeader, SheetTitle as PreviewSheetTitle, SheetDescription as PreviewSheetDescription, SheetFooter as PreviewSheetFooter } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewSheetTrigger asChild>
                <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Open sheet</button>
              </PreviewSheetTrigger>
              <PreviewSheetContent>
                <PreviewSheetHeader>
                  <PreviewSheetTitle>Sheet preview</PreviewSheetTitle>
                  <PreviewSheetDescription>
                    Use this seeded layout to confirm sizing and hierarchy before replacing with real content.
                  </PreviewSheetDescription>
                </PreviewSheetHeader>
                <div className="mt-6 text-sm text-muted-foreground">Preview body content</div>
                <PreviewSheetFooter>
                  <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Done</button>
                </PreviewSheetFooter>
              </PreviewSheetContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Table',
        requiredExports: ['TableHeader', 'TableBody', 'TableRow', 'TableHead', 'TableCell'],
        imports: 'import { TableHeader as PreviewTableHeader, TableBody as PreviewTableBody, TableRow as PreviewTableRow, TableHead as PreviewTableHead, TableCell as PreviewTableCell } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewTableHeader>
                <PreviewTableRow>
                  <PreviewTableHead>Plan</PreviewTableHead>
                  <PreviewTableHead>Status</PreviewTableHead>
                  <PreviewTableHead>Users</PreviewTableHead>
                </PreviewTableRow>
              </PreviewTableHeader>
              <PreviewTableBody>
                <PreviewTableRow>
                  <PreviewTableCell>Starter</PreviewTableCell>
                  <PreviewTableCell>Active</PreviewTableCell>
                  <PreviewTableCell>8</PreviewTableCell>
                </PreviewTableRow>
                <PreviewTableRow>
                  <PreviewTableCell>Growth</PreviewTableCell>
                  <PreviewTableCell>Trial</PreviewTableCell>
                  <PreviewTableCell>22</PreviewTableCell>
                </PreviewTableRow>
              </PreviewTableBody>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Tabs',
        requiredExports: ['TabsList', 'TabsTrigger', 'TabsContent'],
        imports: 'import { TabsList as PreviewTabsList, TabsTrigger as PreviewTabsTrigger, TabsContent as PreviewTabsContent } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent className="w-full" {...previewProps}>
              <PreviewTabsList className="grid w-full grid-cols-2">
                <PreviewTabsTrigger value="overview">Overview</PreviewTabsTrigger>
                <PreviewTabsTrigger value="activity">Activity</PreviewTabsTrigger>
              </PreviewTabsList>
              <PreviewTabsContent value="overview" className="mt-4 text-sm text-muted-foreground">
                Overview content generated for preview purposes.
              </PreviewTabsContent>
              <PreviewTabsContent value="activity" className="mt-4 text-sm text-muted-foreground">
                Activity content generated for preview purposes.
              </PreviewTabsContent>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'ToggleGroup',
        requiredExports: ['ToggleGroupItem'],
        imports: 'import { ToggleGroupItem as PreviewToggleGroupItem } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent type="single" {...previewProps}>
              <PreviewToggleGroupItem value="day">Day</PreviewToggleGroupItem>
              <PreviewToggleGroupItem value="week">Week</PreviewToggleGroupItem>
              <PreviewToggleGroupItem value="month">Month</PreviewToggleGroupItem>
            </PreviewComponent>`,
    }),
    seed({
        componentName: 'Tooltip',
        requiredExports: ['TooltipTrigger', 'TooltipContent'],
        imports: 'import { TooltipTrigger as PreviewTooltipTrigger, TooltipContent as PreviewTooltipContent } from "__PREVIEW_COMPONENT_IMPORT__";',
        componentTag: `<PreviewComponent {...previewProps}>
              <PreviewTooltipTrigger asChild>
                <button className="inline-flex rounded-md border border-gray-300 px-3 py-2 text-sm font-medium">Hover target</button>
              </PreviewTooltipTrigger>
              <PreviewTooltipContent>
                Seeded tooltip content for a readable browser preview.
              </PreviewTooltipContent>
            </PreviewComponent>`,
    }),
];

export function getCompoundPreviewSeed(componentName: string, exportedNames: string[], importPath: string): CompoundPreviewSeed | null {
    const entry = SEEDS.find(seedEntry =>
        seedEntry.componentName === componentName &&
        seedEntry.requiredExports.every(required => exportedNames.includes(required)));

    if (!entry) return null;

    return {
        imports: entry.imports.replaceAll('__PREVIEW_COMPONENT_IMPORT__', importPath),
        componentTag: entry.componentTag,
    };
}
